### ISSUE TITLE
Abandoned?

### ISSUE THREAD

**Issue by sid-kap** [cchalmers/ihaskell-diagrams#1]
Is this project abandoned? I noticed that this project seems similar to (and much more featureful than!) the ihaskell-diagrams project at https://github.com/gibiansky/IHaskell/tree/master/ihaskell-display/ihaskell-diagrams.

**Comment by cchalmers** [comment]
Kinda. I just started this when I was playing with ihaskell, but I haven't used ihaskell in a while. I half intended to be a replacement of the one you linked.

If you'd like I could update it. I should be able to get to it some time this week. Let me know if there's any other features you want to see.

**Comment by sid-kap** [comment]
That would be nice, I suppose, if you could update it, but don't sweat it -- I managed to get the SVG backend working anyways by copying some of your code into my project. 

Also, I personally believe it would be best to make the changes in gibiansky's repo rather than maintaining a separate repo, but I guess that depends on whether gibiansky is OK with adding lots of dependencies (or lots of IFDEFs in the cabal and source files) to that repo.
